### ISSUE TITLE
Request for mp3 file output

### ISSUE THREAD

**Issue by LookAppropriate** [diglet48/restim#1]
This is a very useful utility that feels better in my opinion than the other web-based ones. Given that mp3 files are very much smaller than wav files, could you add an option to output mp3 instead of wav in the program funscript_to_wav.py please? I know this can be done on the command line with ffmpeg for example, but it would be helpful if this was included. Perhaps you could also consider having -o specify a format (such as mp3 or wav) instead of the filename, where the output filename could be the same as the input, but simply with a different extension?

**Comment by diglet48** [comment]
Sorry for the delay, I should check this place more often.

This is a good idea, I will look into this.

**Comment by diglet48** [comment]
Implemented in 02e0a83
