### ISSUE TITLE
1:15 Mac OS (11.7.10) Compilation of Source Not Connecting to VLC

### ISSUE THREAD

**Issue by forthr1ght** [diglet48/restim#10]
I downloaded 1:13 and was able to figure out how to get it working under Python on Mac OS (thanks for that file and that support). 1:13 connects just fine to VLC using VLC remote/server.  Downloaded 1:15 and was able to get that up and running, but when I attempt to connect to VLC I just get a "Attempting to connect..." message. If I revert back to 1:13 then it works fine again. 

I'm pretty happy using 1:13, but I would like to be able to implement frequency, pulse, and other options in the newer versions. I'm using a bog standard English language version of Python and VLC, so I don't think it's a language pack issue (as you had identified in another case). This is the only error python threw when I was compiling the program:

"MacBook-Pro-2:restim-1.15$ python3 restim.py
QLayout: Attempting to add QLayout "" to FivePhaseSettingsWidget "tab_fivephase", which already has a layout
QLayout: Attempting to add QLayout "" to VolumeControlWidget "tab_volume", which already has a layout
libpng warning: iCCP: known incorrect sRGB profile
INFO:restim.websocket:websocket server active at localhost:12346
INFO:restim.tcp_udp:TCP server active at localhost:12347
INFO:restim.tcp_udp:UDP server active at localhost:12347
qt.qpa.fonts: Populating font family aliases took 522 ms. Replace uses of missing font family "Sans-serif" with one that exists to avoid this cost. 
INFO:restim.main:funscript mapping changed, re-linking scripts." [This is the attempt to connect to VLC, which fails in 15]

Here's the comparison to the log for 13:
"MacBook-Pro-2:restim-1.13$ python3 restim.py
QLayout: Attempting to add QLayout "" to FivePhaseSettingsWidget "tab_fivephase", which already has a layout
QLayout: Attempting to add QLayout "" to VolumeControlWidget "tab_volume", which already has a layout
libpng warning: iCCP: known incorrect sRGB profile
INFO:restim.script_mapping:detecting funscripts from: ``
INFO:restim.websocket:websocket server active at localhost:12346
INFO:restim.tcp_udp:TCP server active at localhost:12347
INFO:restim.tcp_udp:UDP server active at localhost:12347
INFO:restim.buttplug:Not starting buttplug WSDM client because disabled in settings.
qt.qpa.fonts: Populating font family aliases took 321 ms. Replace uses of missing font family "Sans-serif" with one that exists to avoid this cost. 
INFO:restim.main:funscript mapping changed, re-linking scripts.
INFO:restim.media:connected
WARNING:media.VLC:error detecting media duration: Failed to load media
INFO:restim.media:file loaded
INFO:restim.media:play-on-load
INFO:restim.script_mapping:detecting funscripts from: `/Volumes/MT Portable 2TB - APFS/ESTIM/Rhythms of Desire - Extended edition (PMV)/Rhythms of Desire - Extended edition (PMV).mp4`

THANKS

**Comment by diglet48** [comment]
This was fixed in bdd5216. If you want a fix now, you can download the latest code from the repository. I will make a new release with this fix in a few days.

**Comment by forthr1ght** [comment]
Thanks!  In the interim I downloaded 1:14 and got RoD working for all funscripts. A lot of fun. I'll update the source and re-compile.

Your work on this program and engagement on discord, milovana, github has been exceptional. I'm very grateful and I know that many in the community are as well.
